adoptium/aqa-test-tools

TestResultSummaryService/routes/deleteUnusedOutput.js
TestResultSummaryService/routes/index.js

Orphan outputs maybe created in output. deleteUnusedOutput is
created to delete these orphan outputs. This API is for DB clean
up purpose only.

Add deleteUnusedOutput api

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/JenkinsInfo.js

Ignore invalid build url when the error is 404
Fixes: #4

Check Jenkins query exception message

---

test-result-summary-client/src/PerfCompare/PerfCompare.jsx

There is no need to check for server name. Server name may change and we
may monitor mutiple Jenkins servers.

remove server name check for perf compare

---

TestResultSummaryService/routes/getBuildHistory.js

Change to allow multiple build names in getBuildHistory call 
Validation: 
Called `http://localhost:3000/api/getBuildHistory?type=Perf&buildName=Daily-ODM&buildName=Daily-ODM-Linux-PPCLE64&buildName=Daily-ODM-openJ9&status=Done&limit=100&asc` and for the following response:

Pat - API 

---

PerfNext/.gitignore
PerfNext/README.md
PerfNext/app.js
PerfNext/app/apis/BenchEngine/parser.js
PerfNext/config/benchmarks/buckets_metric.xml
PerfNext/config/benchmarks/data_simple/Liberty.xml
PerfNext/config/benchmarks/data_simple/SPEC.xml
PerfNext/package-lock.json
PerfNext/public/lib/js/util.js
PerfNext/public/pages/schedule.html

**Fetch Credentials from a File**
• Enabled the fetching of credentials from a JSON file in order to make PerfNext more configurable and to avoid having that information scattered in the code
• Updated README.md and .gitignore for the credentials storage change
**Defunct Items**
• Hid the lean launcher temporarily since it's broken and not used anymore. It might be repurposed later.
• Hid the extra 3 menu options (i.e. Tasks, Debug, Load and Save) in order to avoid confusion as they are dummy placeholders and don't have any functionality
**Iteration Loop**
• Changed for loop to a while loop since the style of for loop (`for iteration in {1..${iterations}}`) being used earlier isn't supported by `#!/bin/sh`
○ The benchmark script is launched through Jenkins Pipeline using sh (i.e. sh …

Several Enhancements & Fixes for Credentials, Defunct Items, Iteration Loop & Benchmarks

---

TestResultSummaryService/routes/getPerffarmRunCSV.js
test-result-summary-client/src/PerfCompare/PerfCompare.jsx

Issue: #23
- Removed the hard-coded string http://perffarmServer as a sample Build Server URL.
- Used variables instead by parsing information from trssConfig.json file. The clients create/edit the configure file.
- Updated README.md for instructions.
Signed-off-by: sophiaxu0424 <xmh1989@my.yorku.ca>

Update TRSS/TRSC Build Server

---

TestResultSummaryService/Database.js
TestResultSummaryService/routes/getTotals.js
TestResultSummaryService/routes/index.js

- query can contain url, buildName, buildNum, level, group, platform and
impl
- this API returns aggregated numbers of total, executed, passed, failed
and skipped tests based on the sdkID
- sdkID is a combo of Jenkins url, buildName, buildNum for now. It
should be shas once we have the info stored
- level, group, platform are optional params
- impl needs to be added once we have impl info stored
Issue: #43

API for getTotals ( query )

---

TestResultSummaryService/DataManager.js
test-result-summary-client/src/Build/AllTestsInfo.jsx

- Due to 16M document size limit, only store last ~12M output
- if tests obj is empty, display N/A
Fixed: #57

Store last 12M of output

---

PerfNext/machines/master_machine_list.xsd
PerfNext/machines/template_master_machine_list.xml

• Added a machine schema for machine data file
• Added a template machine data file
Closes https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/71
Another Related Issue: https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/issues/25
Signed-off-by: piyush286 <piyush286@gmail.com>

Add Machine Schema for PerfNext

---

test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/BuildTable.jsx
test-result-summary-client/src/Build/TopLevelBuilds.jsx

- Perf Test should display the parent builds in the first layer, by clicking each parent build's link would give information of all its child builds.
Issue: #24

Updated Perf Test display with parent and children builds separately

---

test-result-summary-client/src/Dashboard/Widgets/DateRangePickers.jsx

- call set/getExtremes() from axis instead of props

Fix issue with perf dashboard

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/README.md
TestResultSummaryService/plugins/README.md
TestResultSummaryService/plugins/examplePlugin.js
TestResultSummaryService/plugins/index.js

- With this structure, users can define their own plugins. The plugin
files can be added under `plugins` folder or they can be stored in
another repo. The program will try to find all available files under
`plugins` folder at runtime.
- Example plugin is added
- Updated readme
Closes: #99

Support Plugin structure

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/package-lock.json
TestResultSummaryService/package.json
TestResultSummaryService/parsers/ParentBuild.js
TestResultSummaryService/perf/BenchmarkMathCalculation.js
TestResultSummaryService/perf/DataManagerAggregate.js
TestResultSummaryService/plugins/DataManagerPerf.js

This PR is referred to PR #85 (which was closed by mistake)
1. Add "Perf" type option to parent build parser, assure that only builds started with "PerfNext" would be updated with aggregateInfo
2. Aggregated information added to master/child builds with type "Perf" in the database.
3. Move the Benchmark Math calculation from the client side to backend to save the operation time.
Issue: #24 #70 #73 AdoptOpenJDK/openjdk-tests#850
Signed-off-by: sophiaxu0424 <xmh1989@my.yorku.ca>

Add aggregate info to each node(newly updated)

---

PerfNext/config/benchmarks/data_simple/Liberty.xml
PerfNext/config/benchmarks/data_simple/ODM.xml
PerfNext/config/benchmarks/data_simple/SPEC.xml
PerfNext/public/lib/js/util.js
PerfNext/public/pages/schedule.html

- Closes #32
- Removed hard coded hardware environment variables
- Extended functionality to look for capability in order to populate HW specific variables
- CPU Affinity calculations fixed, also name changed to 4-way instead of cores
- Soft coded NUM_THREADS variable to replace hard coded MULTITHREAD variable
Signed-off-by: Awsaf Arefin Sakif <awsaf.sakif@ibm.com>

Extend dynamic fetching of HW environment variables

---

TestResultSummaryService/package-lock.json
TestResultSummaryService/parsers/BenchmarkParser.js
TestResultSummaryService/routes/getTabularData.js
TestResultSummaryService/routes/getTabularDropdown.js
TestResultSummaryService/routes/index.js
test-result-summary-client/package-lock.json
test-result-summary-client/package.json
test-result-summary-client/src/App.jsx
test-result-summary-client/src/PerfCompare/PerfCompare.jsx
test-result-summary-client/src/TabularView/TabularView.css
test-result-summary-client/src/TabularView/TabularView.jsx
test-result-summary-client/src/TabularView/TabularViewConfig.json
test-result-summary-client/src/TabularView/index.js

- Closes AdoptOpenJDK#37
- Current filters: benchmark, platform, cell color
- Allows comparison between different jdk versions and types
- Cell on click redirects to Perf Compare
- Perf Compare changed to fill in values from URL on load
- Added sdkResource to parser, will be added as field to database
Co-authored-by: Piyush Gupta piyush286@gmail.com
Signed-off-by: Awsaf Arefin Sakif <awsaf.sakif@ibm.com>

Adding Tabular View for comparing baseline and test builds for selected platforms and metrics

---

PerfNext/app/apis/BenchEngine/parser.js
PerfNext/setup.sh

- Disabled echo of executed commands in Jenkins in order to reduce the output size, making the console output more easier to read and parse
Signed-off-by: Piyush Gupta <piyush286@gmail.com>

Disable Echo of Executed Bash Commands in Jenkins Output

---

TestResultSummaryService/parsers/BenchmarkMetric.js
TestResultSummaryService/parsers/BenchmarkMetricRouter.js
TestResultSummaryService/parsers/BenchmarkParser.js

Closes #124 
1. Removed Regex repeat  & removed regex repeat check
2. OuterRegex is factored out from [Benchmark].[metrics].[outerregex] to [Benchmark].[outerregex]
3. change to liberty hard-coded number regex so it won't be affected by # of warmup runs
4. Removed checks that checks fields in the BenchmarkMetric.js file
5. Added comments BenchmarkMetric.js to give general structure of what a benchmark metric should look like

Parser update

---

TestResultSummaryService/parsers/BenchmarkMetricRouter.js
TestResultSummaryService/parsers/BenchmarkParser.js
TestResultSummaryService/perf/DataManagerAggregate.js
TestResultSummaryService/plugins/DataManagerPerf.js
TestResultSummaryService/routes/getTabularData.js
TestResultSummaryService/routes/getTabularDropdown.js
test-result-summary-client/package-lock.json
test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader3.jsx
test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
test-result-summary-client/src/PerfCompare/PerfCompare.jsx
test-result-summary-client/src/PerfCompare/lib/ExtractRelevantJenkinsTestResults.js
test-result-summary-client/src/TabularView/TabularView.jsx

Related to https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/136 https://github.com/AdoptOpenJDK/openjdk-tests/issues/1144 https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/37
Tabular View Changes
- Enabled the setting of JDK date (i.e. benchmarkProduct) to be dynamic instead of expecting the launch agents such as PerfNext or TestKitGen to set it.
○ JDK date is used on Tabular View to show the data of latest baseline and test builds before that JDK date.
- Updated the Tabular View query for fetching unique build names, sdk resource and build servers, options that are displayed for choosing desired baseline or test builds for comparison
○ Query didn't have the correct SDK resource location.
- Resolved the issue of Tabular View incorrectly setting states for dropdown options …

Enhancements for Tabular View & Benchmark Parser

---

TestResultSummaryService/routes/getTestAvgDuration.js
TestResultSummaryService/routes/index.js

getTestAvgDuration calculates the average test duration from the most
recent matched builds (default limit is 200)

Add getTestAvgDuration API

---

TestResultSummaryService/routes/getTestAvgDuration.js

- Add ability to divide tests into number of buckets (based on test
duration) to get optimal throughput overall
- new param: `bucketCount` Optional. The number of buckets the tests
will be divided into. The default value is 1
- change `testName` parameter from required to optional

Enhance getTestAvgDuration API

---

test-result-summary-client/src/TestCompare/TestCompare.jsx

- added Remove TimeStamp button to hide timeStamp from Jenkins Output
- added Apply DeepSmith Match button to process data for comparison
Issue: runtimes/backlog/issues/159

Support removing timeStamp and applying deepSmith match for comparison

---

test-result-summary-client/src/Build/TopLevelBuildTable.jsx
test-result-summary-client/src/Build/TopLevelBuilds.jsx

As we monitor more builds and keep longer history, the first landing
page becomes slow. The reason is that we are trying to prepare all data
regardless it will show up or not. In the landing page, due to table
pagination we only show the latest 5 builds from each pipeline. The rest
does not need to be queried until the user clicks on the next page.
This PR updates the logic to simplify TopLevelBuilds.jsx. We separate it
to contain React components. Each table/pipeline is one component. Each
component keep tracks its own pagination. Query is based on the table
pagination.

Performance enhancement

---

test-result-summary-client/src/Build/Summary/ResultSummary.jsx

All jck builds that are triggered in nightly will show up in the Grid view
Issue: #191

Add jck in the Grid view

---

test-result-summary-client/src/Build/TestTable.jsx

During search, we only have info about the test, not the build. Disable
the git issue icon (for open git issue) for search. If this feature is
needed, we can update API to return buildId during search.
Fixes: #195

Fix search error

---

TestResultSummaryService/routes/getTabularData.js
test-result-summary-client/src/TabularView/TabularView.jsx

#136 #173 
- Updated TabularView to display one or more benchmarks after the new design of multiple benchmarks applied in aggregateInfo.

Updated TabularView to handle one/more benchmarks in Adopt Perf Builds

---

test-result-summary-client/src/PerfCompare/PerfCompare.jsx
test-result-summary-client/src/PerfCompare/lib/ExtractRelevantJenkinsTestResults.js

#136 #171 
- Updated perfCompare to display one or more benchmarks under one builds using the new design of aggregateInfo

Updated PerfCompare to handle one/more benchmarks in Adopt Perf Builds

---

TestResultSummaryService/parsers/Parser.js
TestResultSummaryService/perf/DataManagerAggregate.js
test-result-summary-client/src/PerfCompare/PerfCompare.jsx

https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/201
- fixed displaying bugs in benchmarkName/variant showing in perfCompare
- fixed jdkDate regex bug in Parser.js
- fixed bug of `validAggregateInfo` in DataManagerAggregate

Fixed bugs in perfCompare, Parser and aggregateInfo

---

TestResultSummaryService/LogStream.js

url.parse is not needed in streaming as we can directly concatenate the
url

Remove url.parse

---

TestResultSummaryService/routes/getBenchmarkMetricProps.js
TestResultSummaryService/routes/getParserProps.js
TestResultSummaryService/routes/index.js
test-result-summary-client/src/PerfCompare/PerfCompare.jsx
test-result-summary-client/src/TabularView/TabularView.jsx
test-result-summary-client/src/utils/perf.js

Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/211
- Updated getParserPropes.js to receve benchmarkName, so it would return the metrics directly as needed
- Updated perfCompare and TabularView accordingly
- Updated utils/perf.js file

CleanUp: updated getParserProps.js to remove duplicate logic

---

test-result-summary-client/src/PerfCompare/PerfCompare.jsx

https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/215
- Updated those values for displayErrorMessage, higherBetter,etc.
- Fixed small bugs in displaying values of different benchmarks.

CleanUp: Remove null/undefined/empty values in PerfCompare

---

TestResultSummaryService/Database.js

If user doesn't provide the buildResult, we use default `SUCCESS` or `UNSTABLE`
fixes: #242

add buildResult into getAvgDuration query

---

test-result-summary-client/src/Build/Summary/ResultSummary.jsx

console.log(groups[group]) at [ResultGrid](https://github.com/OscarQQ/openjdk-test-tools/blob/831591802510f7ecd50a5fb771e5ea0e975392cb/test-result-summary-client/src/Build/Summary/ResultGrid.jsx#L57) 
```
buildId: "5ecc4cb43b161d1310c235da"
buildResult: "SUCCESS"
buildUrl: "https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64_aix_Nightly/882/"
hasChildren: true
testSummary: {total: 366, executed: 147, passed: 147, failed: 0, disabled: 27, …}
_id: "5ecc4b9c3b161d1310c22729"
__proto__: Object
```
we are interested in _id, not buildId, when redirect to parallel builds
localhost seems working, I can see the expected page
fixes: #247

fix the link for parallel builds

---

TestResultSummaryService/parsers/Test.js

This draft PR has my own testing (console.log etc) and I will delete them when convert to the formal PR. 
Here is how I test my changes: 
1. test located at [backend.js](https://github.com/OscarQQ/openjdk-test-tools/blob/e8486d92ca748cf512e01b500486abae95871d73/TestResultSummaryService/backend.js#L9) It will load a test parser and parse a predefined string. Duration is assigned only when testName == startTestName == finishTestName. When I change any of the test names, duration is assigned to null (expected)
Sample output:
```
testname!    jck_custom_0
startTestName   jck_custom_1
starttime    1590098570256
finishTestName   jck_custom_0
finishTime    1590098577444
duration        null
```
2. console.log() in [test parser](https://github.com/OscarQQ/openjdk-test-tools/blob/e8486d92ca748cf512 …

add testName validation in test parser

---

test-result-summary-client/src/PerfCompare/PerfCompare.jsx

Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/237
- Fixed the undefined bug for units in PerfCompare

Fixed the undefined bug in units in PerfCompare

---

TestResultSummaryService/parsers/Utils.js
test-result-summary-client/src/Build/Summary/ResultGrid.jsx

- use UNSTABLE instead of PARTIAL-SUCCESS in perf
- add  Build Result is from parser, (not CI build) in perf tooltip
fixes: #267

TRSS grid perf cell fixing

---

TestResultSummaryService/routes/getTestByVersionInfo.js
TestResultSummaryService/routes/index.js

getTestByVersionInfo returns the latest test builds with matched java
version info. Regex is expected, so please escape the special
characters.

Add getTestByVersionInfo API

---

TestResultSummaryService/parsers/BenchmarkMetric.js

• Added parser for Renaissance tests
• Remove unit from metric name for Liberty Startup test
• Renamed Liberty Startup to conform to the naming convention
Related Issues:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1127
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1770
Signed-off-by: Piyush Gupta <piyush286@gmail.com>

Add Parser for Liberty Throughput

---

TestResultSummaryService/parsers/Parser.js

add Java Version tags in jenkins console output
1. =JAVA VERSION OUTPUT BEGIN=
2. =JAVA VERSION OUTPUT END=
update regex
related: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1840
related issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/269
enhancement of: https://github.com/AdoptOpenJDK/openjdk-test-tools/pull/270

enhance java version extraction

---

TestResultSummaryService/BuildMonitor.js
TestResultSummaryService/routes/index.js
TestResultSummaryService/routes/updateKeepForever.js
package-lock.json
test-result-summary-client/src/Build/TopLevelBuildTable.jsx

Once the keepforever checkbox is selected for a build, this build will
not be removed even if we reach max # builds to keep.
Ideally, this keepforever option should only be available for admin.
This should be updated once we have authentication added.
Resolves: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/288

Add keepforever option

---

TestResultSummaryService/parsers/Parser.js
TestResultSummaryService/parsers/Test.js
test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/GitNewIssue.jsx
test-result-summary-client/src/Build/table.css

- extract rerun link from Jenkins console output
- show link to grinder rerun when open the git new issue tab
related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/258
Signed-off-by: OscrQQ <Yixin.Qian@ibm.com>

add grinder rerun link in git new issue

---

test-result-summary-client/src/TabularView/TabularView.jsx
test-result-summary-client/src/TabularView/TabularViewConfig.json

https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/264
- bug fixed
- midified the default display from Openjdk8 to 11 in Tabular View

Fix Loads Multiple Times bugs in TabularView

---

TestResultSummaryService/routes/getErrorInOutput.js
TestResultSummaryService/routes/index.js
test-result-summary-client/src/Build/GitNewIssue.jsx

- create a new parser to get 10 lines of failure output
- fix the bug when rerunLink is undefined
- related: #258 

capture failure console output in git new issue

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/JenkinsInfo.js
TestResultSummaryService/LogStream.js
TestResultSummaryService/package.json
TestResultSummaryService/parsers/ParentBuild.js
TestResultSummaryService/parsers/Test.js

- Due to 1G string limit, we cannot store ouptut > 1G. Using http head
request to get the output size in getSize(). If the size > 1G, only
process the last 0.7G. This is a temporary fix, so that TRSS can proceed
and continue processing other builds.
- instead of using Jenkins nodejs API, we change to use `got` to query.
This will allow us to control the query precisely.
- increase regular query timeout from 2secs to 30secs and reduce the
retry from 5 times to 3 times for Jenkins nodejs APIs. It is better to
retry less often with longer timeout
- increase node max memory to 6G

Process large output

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/DataManager.js
TestResultSummaryService/EventHandler.js
TestResultSummaryService/JenkinsInfo.js
TestResultSummaryService/LogStream.js
TestResultSummaryService/backend.js
TestResultSummaryService/package.json
TestResultSummaryService/plugins/DataManagerPerf.js
TestResultSummaryService/plugins/examplePlugin.js
TestResultSummaryService/routes/getJenkins.js
test-result-summary-client/src/Build/AlertMsg.jsx
test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/Output/Output.jsx

Process a large output (700M+) may cause OOM in CI server and/or TRSS.
Update the logic to only process the output < limit. If the output > limit, 
record the error and display in UI. The limit is set to 50M for now as the 
regular build output is ~3M. We can adjust the limit as needed.
This PR also includes the following changes:
- remove try catch in the lower level (LogStream) and the exception will
be caught at the higher level (BuildProcessor), so that we can store the
exception into DB
- add AlertMsg in UI
- add short sleep (2 secs) in between processing each build to avoid overloading
CI server. And 5 secs sleep after getting the output size.
- add log for each CI server request with [CIServerRequest] (for
debugging)
- reduce max memory from 6G to 4G in dev env (to match with …

Only process the output size < limit

---

TestResultSummaryService/Database.js

- Remove . to support test build name without suffix (i.e., _Nightly,
_Releases, etc)
- support case insensitive

Fix regex in buildName

---

test-result-summary-client/src/Dashboard/Widgets/BuildStatus/BuildStatus.jsx

change default OpenJ9 to AdoptOpenJDK in buildStatus widget

---

TestResultSummaryService/Utils.js
TestResultSummaryService/routes/getLogStream.js
TestResultSummaryService/routes/index.js

- the original logic only searches for exactly matched URL.
The base URL may not be exactly the same once we have folder structure on Jenkins.
Updated the logic to do startWith()
- Add getLogStream API for debugging purpose

Improvement in addCredential()

---

TestResultSummaryService/BuildMonitor.js

In the original code, we added the build result check to ensure we do not set streaming when the build is completed.
In this case, the build can be processed directly. We use build result != null to determine if a build is completed or not.
However, we noticed a running build could have result != null. Because this build has a build result, TRSS thinks the
build is completed and tries to process the build in the static way (without streaming). At a later stage, when
TRSS notices this build is still running, it cannot do anything but wait for the build to complete. From the user end, it
looks like the build is set to streaming but no data shows up until the whole pipeline is completed.
Remove build result check when set status to streaming. TRSS will check the build result at a later …

Remove build result check when set status to streaming

---

test-result-summary-client/src/App.jsx
test-result-summary-client/src/Build/BuildDetail.jsx
test-result-summary-client/src/Build/ReleaseSummary.jsx
test-result-summary-client/src/Build/index.js

Fixes #399 
Please find a working demo [here](https://drive.google.com/file/d/1aC7axyHECdxTzeGrDli6Fv-91y3nNtOw/view?usp=sharing).
1. Added a `Release Summary Report` button alongside other build details (https://github.com/adoptium/aqa-test-tools/pull/400/commits/0b7d0ab3358370c1e8f1b3117c1758ecca445b67).
2. On being clicked, the button redirects the user to a `TRSS-Parser`-style Summary report (https://github.com/adoptium/aqa-test-tools/pull/400/commits/0b7d0ab3358370c1e8f1b3117c1758ecca445b67).
3. For each failed test, added a link to possible issues (https://github.com/adoptium/aqa-test-tools/pull/400/commits/b3c1d83ed74356773d7b35ef34c8822b9f6ce599).
4. Add a `Copy to Clipboard` button which enables the user to copy the entire report …

Add Release Summary button and generate corresponding summary report

---

test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/TestTable.jsx

-If a test does not appear in previous build, set to N/A
-Sort test results based on a specific order: FAILED, PASSED, DISABLED, SKIPPED, N/A
- related: https://github.com/adoptium/aqa-test-tools/issues/282

fix testResult of undefined in testTable

---

test-result-summary-client/src/Build/Output/Output.jsx

- add jenkins job link
- related: https://github.com/adoptium/aqa-test-tools/issues/430

fix artifactory link in test output page

---

MachineLearningPrototype/dataCollection/collect_data.py

Solves #447 
1. The pipeline now collects all issues from specified github repositories (open and closed).
2. Labels are added to issue information stored on DB.
3. Total number of open issues are found by counting {'state': 'open'} issues from the DB collection. 
4. Total number of issues are found by counting all documents in the collection.

Add collection of closed issues to DeepAQAtik

---

MachineLearningPrototype/dataCollection/config.json
MachineLearningPrototype/utils/preprocess_data.py

Added the function `extract_jenkins_link_and_testname` in the `preprocess_data.py` file to extract the Jenkins URL and Testnames.
For the Sample input:
```
Failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/34/consoleFull
Failing job link 2: https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux/99
From an internal build `Test_openjdk11_j9_sanity.openjdk_s390x_linux/83/`
From the second internal build Test_openjdk17_j9_sanity.openjdk_s390x_linux/99/ (rhel7s390x-4-3)
[2021-06-18T03:04:20.479Z] jdk_util_0_FAILED
jdk_nio_0_FAILED
```
We get the output:
```
(['https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/34', 'https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux/99', …
```

Added extract_jenkins_link_and_testname function

---

MachineLearningPrototype/dataCollection/collect_data.py
MachineLearningPrototype/utils/preprocess_data.py

Following tasks have been done by calling `extract_jenkins_link_and_testname` function with parameter `issue[body]`:
- With `issue[body]`, used function `extract_jenkins_link_and_testname` to generate `(links_list, names_list)`
- Used  `issue_details["issue_quoted_jenkins_links"]` and `issue_details["issue_quoted_test_names"]` to store in DB.
Attaching Screenshot for the Sample DB:
Depends on the PR [#474](https://github.com/adoptium/aqa-test-tools/pull/474)
Based on the issue [#486](https://github.com/adoptium/aqa-test-tools/issues/486)

Added extracted Jenkins URLs and Testnames to the DB

---

test-result-summary-client/src/Build/Summary/Overview.jsx

Checked failedSdkBuilds is not empty at #490
The problem was 
`{failedSdkBuilds ? <BuildLink id={id} label="SDK Builds and Smoke Tests " link="Failed" buildNameRegex="^(jdk[0-9]{1,2}|Build_)" buildResult="!SUCCESS" /> : <div>SDK builds and Smoke Tests Passed</div>}`
We want to check if failedSdkBuilds array is empty or not, so I added  `(failedSdkBuilds && failedSdkBuilds.length)` 
and it's now:
`{(failedSdkBuilds && failedSdkBuilds.length) ? <BuildLink id={id} label="SDK Builds and Smoke Tests " link="Failed" buildNameRegex="^(jdk[0-9]{1,2}|Build_)" buildResult="!SUCCESS" /> : <div>SDK builds and Smoke Tests Passed</div>}`

Checked failedSdkBuilds is not empty at #490

---

test-result-summary-client/src/Build/PossibleIssues.jsx

The following tasks have been performed :
1. `Created at` and the `State` of the issue columns have been added. (Thanks to the API provided by @llxia)
I am also attaching the sample for the reference:
Solves issue #513 

Added Created at and State columns to the possible issues table

---

TestResultSummaryService/routes/getAllTestsWithHistory.js

In the original logic, we sorted the test history based on the build number. This makes sense when
TRSS only monitors single Jenkins server. The most recent build will have the largest build number.
However, this logic does not make sense when TRSS monitors multiple Jenkins servers. Build name and
build number combination is not unique anymore.
While we still want to keep the ability to show history across different Jenkins servers, this PR
updates the logic to sort test history based on timestamp.

Sort test history based on timestamp

---

test-result-summary-client/src/Build/BuildDetail.jsx
test-result-summary-client/src/Build/ReleaseSummary.jsx

- Use Promise.all() to send queries in parallel to improve the performance
- Remove unnecessary queries
- Use params() to handle special characters in parameter values (i.e., test name)
- Add title and Grid view link
- Show actual build results instead of general message `Test Job Failed`
- Add different icons for UNSTABLE and FAILURE
- separate build and test build results into two different groups
- Sort build names in the report, so Version/Impl/Platform and Parent/Child are grouped together
- Handle errors
- in the performance testing, we increased report generation time from 26 secs to 5 secs
Resolves: adoptium#501 and adoptium#506

Enhance Release Summary Report logic

---

TestResultSummaryService/routes/compareTestDuration.js

`Changelogs`:
- Updated compareTestDuration.js
- Swagger Definition fixed
- Added missing routeDef
**Snapshot**:

 [fix] | SwaggerDef added for route

---

test-result-summary-client/src/Build/PossibleIssues.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx

This is a pull request for issue  #572 
/src/Build/Summary/ResultSummary.jsx
Line 7:8: 'PieChart' is defined but never used no-unused-vars
- Added a comment on line 7
./src/Build/PossibleIssues.jsx
Line 83:52: Expected '===' and instead saw '==' eqeqeq
Line 86:17: 'createdAt' is constant no-const-assign
- Changed 'const' to 'let' on line 81
- Added triple '=' on line 83

Fix warning in TRSS

---

test-result-summary-client/src/Build/PossibleIssues.jsx

This update adds a sorting feature on State in the possible issues page.
Fixes: #589
Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>

Add sort on State on possibleIssues page

---

test-result-summary-client/src/Build/BuildDetail.jsx

the task was to remove a button from the build page. so I have done it, you can see the results below.
before:
After:
Fixes: #626
Signed-off-by: Suhas Khobragade <suhaskhobragade19@gmail.com>

removed release summary report button from buildDetail page.

---

test-result-summary-client/src/Build/Output/Output.jsx
test-result-summary-client/src/Build/ReleaseSummary.jsx

It would seem that the master branch did not actually have the test links implemented. I apologize for the duplicate PR. In this PR, there should be test links for each failed test. This is partial fix of #624 
Fixes: #630 
Signed-off-by: Tommy Tho [tommythowm@gmail.com](mailto:tommythowm@gmail.com)
**Report generated at:** Wed, 30 Mar 2022 18:04:23 GMT 
TRSS [Build](http://localhost:3000/buildDetail?parentId=60e60be6a2e5057f5cda32f2&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](http://localhost:3000/resultSummary?parentId=60e60be6a2e5057f5cda32f2) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux/30/ 
Started by upstream project "build-scripts/jobs/jdk11u/jdk11u-linux-x64-hotspot" build number 991 at 2021-06-26, …

Added test links in failed jobs in TRSS Release Summary Report

---

test-result-summary-client/src/Build/Summary/Overview.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx

Added a `Build Metadata` column to the grid view beside `Build Result` that displays `java -version`.
Includes a couple of fixes to the `ResultSummary.jsx` syntax and aesthetic fixes to the grid view to make it easier to view.
Fixes: #642
Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>

Added `java -version` to the grid view

---

test-result-summary-client/src/Build/ReleaseSummary.jsx

- encode testName in rerun url
- no rerun link for Post Test and Pre Test as they are artificial test targets
Fix: https://github.com/adoptium/aqa-test-tools/issues/658

encode testName in rerun url

---

test-result-summary-client/src/Build/Summary/Overview.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx

- Remove SDK Build Results section
- Rename AQA Test Results section name to Build and AQA Test Results
- Display the warning message if no JDK build job gets triggered
Resovles: https://github.com/adoptium/aqa-test-tools/issues/665

Display warning message in Grid view

---

test-result-summary-client/src/Build/ReleaseSummary.jsx

Related: https://github.com/adoptium/aqa-test-tools/issues/684

Remove rerun link for each failed test

---

TestResultSummaryService/jenkins/trssCodeSync.groovy

With newer version of npm, it tries to download the peer dependencies by default.
While doing so, it complains that we have conflicting peer dependency that can not be resolved in highcharts.
Since forcing update may introduce breaking changes, set --legacy-peer-deps to ignore this requirement.

Add --legacy-peer-deps for npm

---

TestResultSummaryService/README.md
TestResultSummaryService/frontend.js
TestResultSummaryService/package-lock.json
TestResultSummaryService/package.json
TestResultSummaryService/parsers/Test.js
TestResultSummaryService/routes/index.js
TestResultSummaryService/routes/test/testParserViaFile.js
TestResultSummaryService/routes/test/testParserViaLogStream.js

- Update the test parser logic to resolve the problem in https://github.com/adoptium/aqa-tests/issues/3792#issuecomment-1164482604
- Add API rate limit to avoid large number of repeated queries to our public APIs
- Add test for testing parser
- Update readme - Node version should be 16+
Related: https://github.com/adoptium/aqa-tests/issues/3792

Update the test parser logic and add API rate limit

---

test-result-summary-client/.npmrc
test-result-summary-client/src/utils/Utils.js

- Add option to connect Adoptium TRSS API for PR testing (i.e., Netlify)
- Set npm default option in .npmrc
Related: https://github.com/adoptium/aqa-test-tools/issues/593

Add option to connect Adoptium TRSS API

---

test-result-summary-client/src/Build/PossibleIssues.jsx

resolves: https://github.com/adoptium/aqa-test-tools/issues/721
Fix date sorting, add default issue sort

Display open issues before closed ones in TRSS possible issues

---

TestResultSummaryService/DataManager.js
test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx

related: https://github.com/adoptium/aqa-tests/issues/3431, https://github.com/adoptium/aqa-test-tools/issues/734 and https://github.com/adoptium/aqa-tests/pull/4030

Support rerun test builds

---

test-result-summary-client/src/Build/Summary/ResultSummary.jsx

Fixes #765 
Update regex to use non-capture group to ignore extra words (release or prototype)
Signed-off-by: Shelley Lambert <slambert@gmail.com>

Update regex to ignore extra words in buildName

---

test-result-summary-client/src/Build/Summary/ResultGrid.css
test-result-summary-client/src/Build/Summary/ResultGrid.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx
test-result-summary-client/src/Build/TestTable.jsx
test-result-summary-client/src/utils/Utils.js

related: https://github.com/adoptium/aqa-test-tools/issues/770
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

Support rerun builds in UI

---

TestResultSummaryService/routes/getAzDoRun.js
TestResultSummaryService/routes/index.js
test-result-summary-client/src/PerfCompare/PerfCompare.jsx
test-result-summary-client/src/PerfCompare/lib/AzDoRunJSON.js

This is step 1 of porting TRSS to work with Azure Devops.
For now, this will only support the perf compare feature which takes two Azure DevOps URL's and scrapes the metrics using the built-in TRSS parsers.
At some point as a next step I'd like to get the runs imported into the DB but I'd prefer to do this in a follow-up PR to avoid a single massive changeset.

initial AzDo port to support perf compare

---

TestResultSummaryService/JenkinsApiQuery.js
TestResultSummaryService/routes/getBuildStages.js
TestResultSummaryService/routes/index.js

This is the first step of resolve #777. In this PR, we build the structure to call Jenkins API (using getBuildStages as an example). In the future PR, we will insert the stage info into DB, so that we can analyze all build stages info.
related: https://github.com/adoptium/aqa-test-tools/issues/777

Add getBuildStages API

---

TestResultSummaryService/routes/getAzDoRun.js

Using startsWith is safer as it allows users to name the jobs more freely

fix naming for perf compare job in AzDo

---

test-result-summary-client/src/Build/ReleaseSummary.jsx

resolved: https://github.com/adoptium/aqa-test-tools/issues/814

Show Rerun builds regardless the results

---

test-result-summary-client/src/Build/ReleaseSummary.jsx
test-result-summary-client/src/Build/Summary/BuildStatus.jsx
test-result-summary-client/src/Build/Summary/BuildStatusIcon.jsx
test-result-summary-client/src/Build/Summary/Overview.jsx
test-result-summary-client/src/Build/Summary/ResultSummary.jsx

Add message/icon to show TRSS status

---

TestResultSummaryService/Database.js

Fixes https://github.com/adoptium/aqa-test-tools/issues/850

Return original _id in getTotals request

---

TestResultSummaryService/BuildProcessor.js
TestResultSummaryService/JenkinsInfo.js
TestResultSummaryService/routes/deleteBuildsAndChildrenByFields.js
TestResultSummaryService/routes/index.js
TestResultSummaryService/routes/rescanBuild.js

- add 2 secs sleep between each retry
- add AuditLogs when the error code is 404 (for debugging purposes)
- create rescanBuild API to rescan
resovles: https://github.com/adoptium/aqa-test-tools/issues/852

Create rescanBuild API

---

TestResultSummaryService/DataManager.js
TestResultSummaryService/JenkinsInfo.js
TestResultSummaryService/routes/index.js
TestResultSummaryService/routes/test/getJenkinsBuildInfo.js

When querying a build, TRSS will retry 3 times.
In the case of an error, the build will move back to the queue if the return code from Jenkins API is not 404. 
If the return code is 404, x-jenkins header is checked to ensure the error code is from Jenkins (not nginx). 
In this case, it means the build has an invalid url or is expired. retry function returns 404 and TRSS will stop processing this build. 
Otherwise, the error will be ignored (network issue) and the build will move back to the queue.
- sleep is removed to increase efficiency and reliability. We will check the header in the response to determine the invalid/expired build case.
- test API getJenkinsBuildInfo is added
- fix log issue
related: https://github.com/adoptium/aqa-test-tools/issues/852

Update build retry logic

---

TestResultSummaryService/routes/getTestBySearch.js
TestResultSummaryService/routes/getTestByTestName.js
TestResultSummaryService/routes/getTestNames.js
TestResultSummaryService/routes/index.js
test-result-summary-client/src/AdvancedSearch/AdvancedSearch.jsx
test-result-summary-client/src/AdvancedSearch/InputAutoComplete.jsx
test-result-summary-client/src/AdvancedSearch/InputSelect.jsx
test-result-summary-client/src/AdvancedSearch/index.js
test-result-summary-client/src/App.jsx
test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/TestTable.jsx
test-result-summary-client/src/Search/SearchTestResult.jsx
test-result-summary-client/src/Search/index.js

resolves: https://github.com/adoptium/aqa-test-tools/issues/854

Add advanced search

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependabot.yml

Fix issue #882 
Changed uses as `github/codeql-action/init@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff `
and added the dependabot.yml file as mentioned.

Update codeql github workflow to use latest version and enable dependabot

---

.github/workflows/codeql-analysis.yml

Related: https://github.com/adoptium/aqa-test-tools/issues/882
We previously update init, but missed updating action.  Other whitespace and quote changes seem to have been automatically applied by Visual Studio Code, not sure if it is preferred or not, I did not initiate those changes.

Update the codeql-action/analyze line

---

test-result-summary-client/src/Build/DeepHistory.jsx

A draft of the issue #837 
I tried to make the table sort by the starting time.

Sort by start time

---

test-result-summary-client/src/Dashboard/Widgets/Graph/Renaissance.jsx

Fixes Issue #874.   We made following improvements: 
- Use length instead of size to check for valid values array
- Convert time into epochs to be sorted arithmetically by mathjs/sort
- Display the series with the correct format 
Done with @tpbui

Re-enabling Renassiance graph 

---

test-result-summary-client/cypress/integration/testInfo.js
test-result-summary-client/src/Build/BuildTable.jsx
test-result-summary-client/src/Build/Summary/ResultGrid.jsx

resolve: https://github.com/adoptium/aqa-test-tools/issues/878

Set build limit to 1

---

test-result-summary-client/src/PerfCompare/lib/PerffarmRunJSON.js

Fix separate in perf
Signed-off-by: longyuzhang <longyu.zhang@ibm.com>

Fix separate in perf

---

TestResultSummaryService/BuildMonitor.js

If a large number of builds (>5) are launched in a short period, TRSS only monitors the last 5 builds.
To avoid this, set the minimum number of monitored builds to 10.

Set the minimum number of monitored builds to 10

---

TestResultSummaryService/package-lock.json
TestResultSummaryService/package.json
TestResultSummaryService/routes/getAllChildBuilds.js
TestResultSummaryService/routes/getAuditLogs.js
TestResultSummaryService/routes/getBuildList.js
TestResultSummaryService/routes/getChildBuilds.js
TestResultSummaryService/routes/getData.js
TestResultSummaryService/routes/getErrorInOutput.js
TestResultSummaryService/routes/getJenkins.js
TestResultSummaryService/routes/index.js
TestResultSummaryService/routes/test/getJenkinsBuildInfo.js

resolves: https://github.com/adoptium/aqa-test-tools/issues/941
fixes: https://github.com/adoptium/aqa-test-tools/issues/935

Upgrade to use express.js v5

---

test-result-summary-client/src/Build/Summary/ResultSummary.jsx

Fixes #816 
Other wrapper scripts / parent jobs (such as AQA_Test_Pipeline) do not run builds, they only run test jobs which always have the version number in the child jobs, so this approach should cover our cases.  This will work for the standard naming used in ci-jenkins-pipelines top-level jobs.

Pull jdkVersion from parent if not in child name

---

test-result-summary-client/src/Build/Summary/ResultSummary.jsx

This PR fixes null error when accessing parenttokens. The error occurs for certain types of parent jobs where the buildName does not match the expected pattern (e.g AQA_Test_Pipeline)

Avoid null error on some parent job types (e.g AQA_Test_Pipeline)

---

test-result-summary-client/src/Settings/Settings.jsx

- Remove buildType JCK from from /admin/settings page
related: https://github.com/adoptium/aqa-test-tools/issues/973

Remove buildType JCK from settings page

---

TestResultSummaryService/DataManager.js
TestResultSummaryService/package-lock.json
TestResultSummaryService/package.json
TestResultSummaryService/parsers/Build.js
TestResultSummaryService/parsers/Parser.js
TestResultSummaryService/perf/DataManagerAggregate.js
TestResultSummaryService/plugins/DataManagerPerf.js
TestResultSummaryService/routes/getBenchmarkMetricProps.js
TestResultSummaryService/routes/getTrafficLightData.js
TestResultSummaryService/routes/index.js
test-result-summary-client/src/AdvancedSearch/InputSelect.jsx
test-result-summary-client/src/App.jsx
test-result-summary-client/src/Components/Button.jsx
test-result-summary-client/src/TrafficLight/TrafficLight.jsx
test-result-summary-client/src/TrafficLight/index.js

resolves: automation/issues/63 and automation/issues/218

Initial check in for Perf Traffic Light

---

test-result-summary-client/src/Build/PossibleIssues.jsx

- Remove  temporarily Related Degree and User Feedback on possible issue page
related: https://github.com/adoptium/aqa-test-tools/issues/978

Remove Related Degree and User Feedback

---

test-result-summary-client/src/Build/PossibleIssues.jsx

Added logic to search for `+repo:adoptium/infrastructure+repo:adoptium/aqa-build` for Adoptium build only and not search these repo for openj9/ibm issues
Resolves: #962 
Signed-off-by :Denny Chacko Jacob <denny.cjacob@ibm.com>

Search adoptium/infrastructure and adoptium/aqa-build for Adoptium build only

---

TestResultSummaryService/routes/getBenchmarkMetricProps.js
test-result-summary-client/src/TrafficLight/TrafficLight.jsx

- group data based on benchmarkName, benchmarkVariant and metricsName
- fix `Cannot set headers after they are sent to the client` in getBenchmarkMetricProps.js
fixes: automation/issues/227

Support benchmark data from multiple platforms

---

TestResultSummaryService/Database.js

Resolves: https://github.com/adoptium/aqa-test-tools/issues/982
Signed-off-by : Denny Chacko Jacob < denny.cjacob@ibm.com>

Test summary numbers for perf Build

---

test-result-summary-client/src/Build/ReleaseSummary.jsx

- Added `react-copy-to-clipboard` module to enable copying of the release summary report.
- Wrapped the copy button with `CopyToClipboard`
Related: https://github.com/adoptium/aqa-test-tools/issues/942

Leverage CopyToClipboard module for copying

---

test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx

Dacapo.jsx matches new datastructure:
1. Since jdkDate is null, derive it from t.timestamp.
2. Extract metric with respect to test.duration and test.benchmarkName instead of tests.testData.metrics
Notes for possible related issues:
-Can optimize the code, currently I believe there are wasteful null values in resultsByJDKBuild due to change 2. 
-Current code assumes only one iteration per benchmark, but there could be multiple iterations.
Fixes: #1049
TRSS local result:

Enabled Dacapo on Dashboard

---

test-result-summary-client/src/Build/TopLevelBuildTable.jsx

Replaced link to /buildDetail with BuildStatus
inside renderBuild when value.tests is null.
Redo of PR #1057, hard reset with upstream before branching to get rid of weird package directory changes. 
TRSS local results: 
Fixes: #1048

Enable Build Tree for Perf Pipeline 

---

test-result-summary-client/src/Build/TopLevelBuildTable.jsx

fixes: https://github.com/adoptium/aqa-test-tools/pull/1063#issuecomment-3059921965

Fix Perf top page empty build issue

---

test-result-summary-client/src/TrafficLight/TrafficLight.jsx

feat: Add Jenkins links to Perf Pipeline build selectors
Adds a "Jenkins Link" next to the "test build" and "baseline build" dropdowns on the Performance Pipeline page. 
This provides a direct link to the selected build's Jenkins job, improving user workflow.
I hope it works
Fixes Issue #1046

Update TrafficLight.jsx with Jenkins links

---

test-result-summary-client/src/TrafficLight/TrafficLight.jsx

The table renders correctly when benchmarks are executed across all platforms. However, if benchmarks are only run on a subset of platforms, the Build Name column does not display all entries. This PR addresses the issue by checking for unique buildNameTitle values across all benchmarks.
Fixes: automation/issues/560

Fix build name column in Traffic Light table

---

test-result-summary-client/src/TrafficLight/TrafficLight.jsx

- Since react setState does not mutate the state immediately, use API call directly.
- Increase the pagination
- Remove unused variables
fixes: automation/issues/582

Fix metricPropsJSON value

---

test-result-summary-client/src/Build/AllTestsInfo.jsx
test-result-summary-client/src/Build/Duration.jsx

Improve TRSS duration display:
- N/A -> no `Start Time`
- Hang suspected -> has `Start Time`, but no `Finish Time`
related: runtimes/backlog/issues/1692

Display N/A and Hang suspected in Duration column

---

test-result-summary-client/src/Build/PossibleIssues.jsx
test-result-summary-client/src/Build/PossibleIssuesByAI.jsx

also, limited the pagination for dedupT AI recommendation to 3 and rendered the Rationale properly.
related: runtimes/automation/issues/664

Git search with test name
