adoptium/aqa-test-tools

- .gitignore
- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/EventHandler.js
- TestResultSummaryService/routes/deleteBuildsAndChildrenByFields.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Settings/Settings.jsx
- before insert new data, check for builds in databaase. If num
of builds > num of builds to keep, remove old builds
- by default, num of builds to keep is 10. User can set it to any
positive number.
- fix display issue in Perf test
Close: #6
> Support build deletion

- TestResultSummaryService/DashboardBuildInfo.json
- TestResultSummaryService/routes/getDashboardBuildInfo.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/Dashboard/Defaults.js
- test-result-summary-client/src/Dashboard/TabInfo.jsx
- test-result-summary-client/src/Dashboard/Widgets/BuildStatus/BuildStatus.jsx
> Read Dashboard build info from a json file

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/PerfCompare/lib/BenchmarkMath.js
- test-result-summary-client/src/PerfCompare/lib/JenkinsRunJSON.js
> Upgrade react-scripts to 2.1.1 due to security vulnerability

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
> Update packages due to security vulnerability

- PerfNext/package-lock.json
- PerfNext/package.json
> Security update

- PerfNext/README.md
- PerfNext/app/apis/machines.js
- Added request to download latest machine data file from url.
- Updated README.md with examples to populate APP_DATA.json.
Closes #33
> Enable PerfNext to fetch machine data file

- TestResultSummaryService/routes/getBuildHistory.js
- test-result-summary-client/src/Dashboard/Defaults.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader3.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/PlatForm.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/index.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
- getBuild API supports multiple buildNames
- Platform selector uses checkboxes and plugs into get API 
- Display multiple lines in graph with toggle 
- Git diff link where available 
- Confidence Interval where available
> JumpStart Work 

- TestResultSummaryService/parsers/Test.js
> Modified parser code to display test build page

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/DeepHistory.jsx
- test-result-summary-client/src/Build/TestPerPlatform.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Search/SearchResult.jsx
> Set LocaleProvider once

- PerfNext/app/apis/machines.js
- PerfNext/public/lib/js/benchmarks.js
- PerfNext/public/lib/js/util.js
- Machine list updates when app is launched.
- Machine list updates when platform is changed.
- Removed unnecessary call to load machines.json, instead now the machine list is generated from the master machine list.
- Closes Issue #34
> Enable dynamic population of machine list

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/BuildProcessor.js
- TestResultSummaryService/DataManager.js
- TestResultSummaryService/parsers/ParentBuild.js
> Added display of adopt url pipeline build

- test-result-summary-client/src/App.jsx
> Remove unused tab

- TestResultSummaryService/Database.js
- TestResultSummaryService/routes/getAllChildBuilds.js
- TestResultSummaryService/routes/getBuildHistory.js
- TestResultSummaryService/routes/getTotals.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Dashboard/Widgets/BuildStatus/BuildStatus.jsx
- test-result-summary-client/src/utils/query.js
- display test results (Failed/Passed/Skipped/Total numbers using
getTotals()) and links
- decrease page refresh rate (refresh every 5 mins)
- upgrade node modules (i.e., antd, react-scripts)
> Display test results

- test-result-summary-client/src/Dashboard/Widgets/BuildStatus/BuildStatus.jsx
> Added platform column in dashboard

- TestResultSummaryService/DataManager.js
> Temporarily limit output size

- test-result-summary-client/src/Build/BuildTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
> Support BlueOcean link for builds under folders

- TestResultSummaryService/DashboardBuildInfo.json
> update jobs in CustomJenkins

- TestResultSummaryService/README.md
> update MongoDB version to 3.4 in readme

- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/BuildTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Dashboard/Widgets/BuildStatus/BuildStatus.jsx
- test-result-summary-client/src/ErrorBoundary.jsx
- test-result-summary-client/src/PerfCompare/lib/PerffarmRunJSON.js
- test-result-summary-client/src/Settings/Settings.jsx
Fix warnings on the client side
> Fix warnings

- PerfNext/public/pages/index.html
- PerfNext/public/pages/result.html
- PerfNext/public/pages/schedule-simple.html
- PerfNext/public/pages/schedule.html
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
Updated all JavaScript and CSS dependencies for all HTML pages
Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/75
Signed-off-by: piyush286 <piyush286@gmail.com>
> Use Third Party Libraries and Frameworks From CDN

- TestResultSummaryService/parsers/BenchmarkParser.js
> Modified buildResult in perf test

- test-result-summary-client/src/Build/TopLevelBuilds.jsx
> Added icon in FV Test

- TestResultSummaryService/DataManager.js
- TestResultSummaryService/parsers/Test.js
> Fixed test parser logic

- SmartMedia/SmartMediaClient/.gitignore
- SmartMedia/SmartMediaClient/index.html
- SmartMedia/SmartMediaClient/package-lock.json
- SmartMedia/SmartMediaClient/package.json
- SmartMedia/SmartMediaClient/server.js
- SmartMedia/SmartMediaClient/src/App.js
- SmartMedia/SmartMediaClient/src/index.js
- SmartMedia/SmartMediaServer/.gitignore
- SmartMedia/SmartMediaServer/index.js
- SmartMedia/SmartMediaServer/package-lock.json
- SmartMedia/SmartMediaServer/package.json
- simple server and client structure
- placeholder for now
> Initial check-in for SmartMedia

- SmartMedia/SmartMediaServer/ArgParser.js
- SmartMedia/SmartMediaServer/getSearchTweets.js
- SmartMedia/SmartMediaServer/index.js
- SmartMedia/SmartMediaServer/package-lock.json
- SmartMedia/SmartMediaServer/package.json
> Added twitter api for Smart Media

- SmartMedia/README.md
- SmartMedia/SmartMediaServer/ArgParser.js
- SmartMedia/SmartMediaServer/getGitCloneInfo.js
- SmartMedia/SmartMediaServer/getSearchTweets.js
- SmartMedia/SmartMediaServer/index.js
> Added git api and readme for Smart Media

- .gitignore
- TestResultSummaryService/BuildProcessor.js
- TestResultSummaryService/DataManager.js
- TestResultSummaryService/EventHandler.js
- TestResultSummaryService/parsers/Test.js
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- update the logic to set parent build status to Done when all child
builds are done
- fix the logic in Test parser. Results array needs to be reset for each
build
- update to use new node v11.4 feature to support readline async and
await
- update client to show build process status
- small fixes
> Update build status logic

- TestResultSummaryService/BuildMonitor.js
- sort buildNum in ascending order and delete older builds first
> Fix deleteOldBuilds()

- test-result-summary-client/src/Build/BuildDetail.jsx
buildNameRegex should be encoded for nginx to work
> Encode buildNameRegex

- TestResultSummaryService/Database.js
- TestResultSummaryService/parsers/Parser.js
- test-result-summary-client/src/Build/BuildTable.jsx
- test-result-summary-client/src/Build/TestPerPlatform.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- parse and disply disabled tests
> Support disabled in TRSS

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
> Upgrade jquery to 3.4.1

- TestResultSummaryService/backend.js
- TestResultSummaryService/frontend.js
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- TestResultSummaryService/routes/populateDB.js
- break TRSS server node into two - frontend.js and backend.js
- frontend and backend will run in parallel
- install npm-run-all to support running in parallel
- remove app.js
Issue: #108
> Support running multiple node in parallel

- TestResultSummaryService/backend.js
- TestResultSummaryService/package.json
Backend server needs credentials in trssConf.json to access Jenkins
> Add trssConf.json parser in backend

- TestResultSummaryService/BuildProcessor.js
- TestResultSummaryService/JenkinsInfo.js
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- Add PublishName info to help identify the build
- upgrade react-scripts to v3.0.1
- upgrade antd to v3.19.3
> Add PublishName info

- TestResultSummaryService/parsers/BenchmarkMetric.js
- TestResultSummaryService/parsers/BenchmarkMetricRouter.js
Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/119
Signed-off-by: JiayaoLin <Jiayao.Lin@ibm.com>
> Added parsers for AcmeAir

- TestResultSummaryService/routes/getAllChildBuilds.js
- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- udpated the logic behind Test Results and Build Results
> Update topLevelBuilds page

- TestResultSummaryService/DashboardBuildInfo.json
- TestResultSummaryService/Database.js
- TestResultSummaryService/package-lock.json
- test-result-summary-client/package-lock.json
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- remove unnecessary filter/regex
- update DashboardBuildInfo.json with new test job names
- update node modules
Fixes: #128
> Update filter logic for new test job names

- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/ResultGrid.css
- test-result-summary-client/src/Build/ResultGrid.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Build/index.js
- Add Grid view for each test build
- upgrade dependent libs
> Add Grid view for test results

- PerfNext/app.js
- PerfNext/app/apis/BenchEngine/parser.js
- PerfNext/public/lib/js/util.js
- Closes #24
- PerfNext launcher will now interleave test and baseline builds when launched together
- Added a 5 second delay to ensure the jenkins job number appears correctly
- Added Jenkins token for authentication
- Minor indentation fixes
Signed-off-by: Awsaf Arefin Sakif <awsaf.sakif@ibm.com>
> Adding ability to launch Interleaved Performance Runs

- test-result-summary-client/src/Build/Checkboxes.jsx
- test-result-summary-client/src/Build/ResultGrid.css
- test-result-summary-client/src/Build/ResultGrid.jsx
- Add platforms, jdkVersion, and jdkImpls filter in Grid view
- align the icons
> Add filters in Grid view

- TestResultSummaryService/routes/getAllTestsWithHistory.js
- TestResultSummaryService/routes/getTestBySearch.js
- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Search/SearchTestResult.jsx
- test-result-summary-client/src/utils/TextFilter.jsx
- modified search and test client side
- modified getTests server side
> Added machine information into test page

- test-result-summary-client/src/Build/ResultGrid.jsx
- For parallel build, we only dispaly the parent build result and link
- Update icons to match to Jenkins server
- Add build status in tooltip
> Support parallal build in ResultGrid

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/Database.js
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- Database.js is updated due to Mongodb client API changes
- handle the case where monitored build is removed
> upgrade dependencies due to vulnerabilities

- TestResultSummaryService/parsers/Test.js
- TestResultSummaryService/routes/getAllTestsWithHistory.js
- test-result-summary-client/src/Build/AllTestsInfo.jsx
- Store pre and post test output
- handle the case where limit is not set
Issue: runtimes/backlog/issues/175
> Store pre and post test output

- TestResultSummaryService/Database.js
> Add database name in the url and add encodeURIComponent

- TestResultSummaryService/DataManager.js
- TestResultSummaryService/Database.js
- TestResultSummaryService/routes/compareTestDuration.js
- TestResultSummaryService/routes/getTestAvgDuration.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- compareTestDuration API compares latest test duration with its history
runs. It returns object with currentAvg and previousAvg
- create common function getAvgDuration() in Database.js
- update getTestAvgDuration.js to use common function getAvgDuration()
in Database.js
- add rootBuildId in all child builds during inital build
parsing/creation for better query performance
- update dependent libs
> Add compareTestDuration API

- TestResultSummaryService/parsers/BenchmarkParser.js
- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/perf/DataManagerAggregate.js
- TestResultSummaryService/plugins/DataManagerPerf.js
- TestResultSummaryService/routes/getTabularData.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader3.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
- test-result-summary-client/src/PerfCompare/PerfCompare.jsx
- test-result-summary-client/src/PerfCompare/lib/ExtractRelevantJenkinsTestResults.js
Issue #106
Issue #136
- modified database rules by moving javaversion and jdkDate to the very top level and related usages in perfCompare and tabularView
- add extra aggregate information to graph ODM
> Show Aggregated Perf Results in Perf Graph View (ODM)

- TestResultSummaryService/routes/compareTestsOutput.js
- TestResultSummaryService/routes/index.js
- TestResultSummaryService/routes/utils/applyDeepSmithMatch.js
- TestResultSummaryService/routes/utils/removeTimeStamp.js
- added api compareTestsOutput
- Support querying build outputs from Jenkins 
- Support processing and comparing Jenkins outputs 
Issue: runtimes/backlog/issues/159
> Support TRSS Server to Compare Jenkins Outputs

- TestResultSummaryService/routes/getOutputByTestInfo.js
- test-result-summary-client/src/TestCompare/TestCompare.jsx
- removeTimestampFlag and applyDeepSmithMatchFlag parameters can be passed to server along with api calling
- server api processes returned data based on these two parameters
Issue: runtimes/backlog/issues/159
> Enabled front-end send removeTimestamp and applyDeepSmithMatch to server

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Search/SearchTestResult.jsx
- new action will find possible issues related to the test
> Add new action in test table

- test-result-summary-client/src/App.jsx
- Set FV Test as default page and renamed to By Pipeline
- Renamed Menu to Test Results
- Put perf related info under one tab, moved Dashboard to bottom of Test Results
Issue: #164
> Re-structured TRSS Menu

- SmartMedia/SmartMediaClient/package-lock.json
- SmartMedia/SmartMediaClient/package.json
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/routes/index.js
- TestResultSummaryService/routes/updateComments.js
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/BuildTable.jsx
- add comments column on build detail page
- remove obsolete code
- upgrade 3rd party libs
Resolve: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/163
> Add comments column

- TestResultSummaryService/parsers/BenchmarkParser.js
- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/perf/DataManagerAggregate.js
- TestResultSummaryService/plugins/DataManagerPerf.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/index.js
- Based on ODM.jsx, added a perf graph for AcmeAir
- Added parsers for adding information to Node version
Issue #119
Issue #106
Signed-off-by: Jiayao Lin <jiayaolinn@gmail.com>
> Add Parsers & Perf Graph for AcmeAir

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
Since we changed the first side menu to By Pipeline, the default page
should be set to By Pipeline.
> Set default page to By Pipeline

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/BuildTable.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader3.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
- test-result-summary-client/src/PerfCompare/PerfCompare.jsx
- test-result-summary-client/src/TabularView/TabularView.jsx
> Code tidy up

- TestResultSummaryService/routes/getBuildHistory.js
- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/TestTable.jsx
> Provide a test summary page for reporting failure

- TestResultSummaryService/parsers/BenchmarkMetric.js
-requested by Node team
Signed-off-by: Dong Hoon Lee <l.donghoon49@gmail.com>
> Acmeair bug fix in BenchmarkMetric

- TestResultSummaryService/README.md
> Update MongoDB version

- TestResultSummaryService/BuildMonitor.js
- test-result-summary-client/src/Settings/Settings.jsx
In Build Monitoring List, we can set streaming or not streaming as required.
Resolve: #174
> Re-enable streaming

- TestResultSummaryService/parsers/BenchmarkMetric.js
- TestResultSummaryService/parsers/BenchmarkMetricRouter.js
- TestResultSummaryService/parsers/BenchmarkParser.js
- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/parsers/Test.js
- TestResultSummaryService/parsers/TestBenchmarkParser.js
- TestResultSummaryService/parsers/Utils.js
- TestResultSummaryService/perf/DataManagerAggregate.js
- TestResultSummaryService/routes/getTabularDropdown.js
-Tested all perf builds before going to benchmarkParser
-fixed regex bug in javaVersion
Issue #136
> Updated parser to make all Perf builds go to test parser first 

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
> Handle jdknext builds

- TestResultSummaryService/perf/DataManagerAggregate.js
- TestResultSummaryService/plugins/DataManagerPerf.js
#136
- Updated AggregateInfo in all builds with one/more benchmarks available
> Updated AggregateInfo to handle one/more benchmarks in Adopt Perf Builds

- test-result-summary-client/src/App.jsx
LocaleProvider is deprecated, so change to use ConfigProvider
> Change to use ConfigProvider

- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- update regex to match the naming convention
- upgrade 3rd party libs
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1643
> Support test job names with subdirs (external tests)

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/JenkinsInfo.js
- TestResultSummaryService/LogStream.js
- TestResultSummaryService/Utils.js
- Add credentials during streaming if it can be found in trssConfig.json
- move addCredential() into Utils.js so it can be used by other files
- only keep audit logs for 30 days
> Add credential for streaming

- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- Added two more pipelines to monitor AcmeairNodejs result for ppc64le
- Fixed bug: statValues in database
- Issue #136
Signed-off-by: Jiayao Lin <jiayaolinn@gmail.com>
> Monitor ppc64le AcmeairNodejs performance result

- test-result-summary-client/src/Build/Summary/ResultGrid.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/utils/Utils.js
- support strinf in JDK_VERSION
- fix the display order
> Support valhalla and corretto build

- TestResultSummaryService/parsers/BenchmarkMetric.js
reopened pull request due to branch issue 
-Added parser for crud/ restCrud/ pingperf/ getting-started quarkus benchmark parsers
related to issue #188
> Add new quarkus benchmark parsers

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
> Add impl = ibm and skip build info if there is no buildParams

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
> Render JDK_IMPL dynamically

- test-result-summary-client/src/Build/BuildTable.jsx
- Added undefined variable check to fix this problem
Issue: #55
> fixes for filter by result in job list

- test-result-summary-client/src/Build/TestTable.jsx
- for openj9 and ibm impl, display openj9 repo
- for other (e.g. hotspot), display adopt tests repo
Issue:#220
> Display different possible issue link based on jdk_impl

- TestResultSummaryService/parsers/BenchmarkMetric.js
• Added parser for Renaissance tests
Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/238
Signed-off-by: Piyush Gupta <piyush286@gmail.com>
> Add Parser for Renaissance

- TestResultSummaryService/routes/getTestAvgDuration.js
fixes: #243
together with this PR https://github.com/AdoptOpenJDK/TKG/pull/73
[ci skip]
> Rename variables in getTestAvgDuration

- TestResultSummaryService/routes/getOutputById.js
- test-result-summary-client/src/PerfCompare/PerfCompare.jsx
- test-result-summary-client/src/TestCompare/TestCompare.jsx
- test-result-summary-client/src/TestCompare/TestInfo.jsx
- test-result-summary-client/src/utils/parseJenkinsUrl.js
- used build url to replace server url, build name, and build num;
- added parser and validation check for build url
Issue: #234 
> Re-designed Test Compare to support buildUrl

- test-result-summary-client/src/Build/Summary/ResultGrid.jsx
> open page in a new tab

- TestResultSummaryService/parsers/BenchmarkParser.js
- TestResultSummaryService/routes/getTabularData.js
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/TabularView/TabularView.jsx
- test-result-summary-client/src/utils/Utils.js
https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/203
https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/224
- 203 fixed
- Enhancement: Show Nightly & Release Pipeline Data in One Column
- Issue 1: Show only platform info
- Issue 2: Query on SDK Resource
- Issue 3: Minor Issue to set benchmarkNVM
- 224 fixed jdkVersion filter
- Other syntax errors (await, etc)
> Bugs fix for TabularView

- test-result-summary-client/src/Build/TestTable.jsx
> change text to icon with tooltip

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/PossibleIssues.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/index.js
- list multiple repos for possible issues
- click repo name will direct to this repo with searching related issues
Issue:#257
> Support listing multiple repos for possible issues

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/Summary/ResultGrid.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- add another param `hasChildren` in the link at ResultGrid
- add build info into every test results
- update two columns (possibleIssues and gitIssues) in TestTable
- show java version in git new issue
fixes: #259
related: #258
> aggregate test results for parent build

- TestResultSummaryService/parsers/Parser.js
> fix javaVersion extraction bug

- TestResultSummaryService/parsers/Test.js
> fix invalid date in deep history

- TestResultSummaryService/parsers/Parser.js
> remove timestamp in java version

- test-result-summary-client/src/Build/TestTable.jsx
> fix pagination size changer in TestTable

- TestResultSummaryService/routes/getHistoryPerTest.js
- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/GitNewIssue.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Build/index.js
- a new tab for git new issue
- list first failure info and count of consecutive failures
- list all machines that make the test fail
- related: #258
> enhance git new issue functionality

- test-result-summary-client/src/Build/GitNewIssue.jsx
> fix typo in git new issue

- test-result-summary-client/src/Build/PossibleIssues.jsx
- possible issues changed from listing repos to listing issues directly
issue: #257 
> Support fetch possible issues from Github repos

- test-result-summary-client/src/PerfCompare/PerfCompare.jsx
Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/227
- bug fixed
> Fixed the bug in PerfCompare

- test-result-summary-client/src/Build/GitNewIssue.jsx
- test-result-summary-client/src/utils/Utils.js
- extract OpenJ9 and OMR SHA if java version is OpenJ9 VM
- build github compare links
- related: #258
> add git diff in git new issue

- test-result-summary-client/src/Build/PossibleIssues.jsx
- each repo displays a table for its possible issues
Issue:#257
> Added displaying repo name for each possible issue

- test-result-summary-client/src/TabularView/TabularView.jsx
https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/265
- bug fixed
> Fixed bug in Tabularview that react table not showing all values

- TestResultSummaryService/DataManager.js
- TestResultSummaryService/Database.js
- TestResultSummaryService/parsers/ExternalTestParser.js
- TestResultSummaryService/parsers/Test.js
- TestResultSummaryService/parsers/Utils.js
- TestResultSummaryService/routes/getApplicationTests.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/ThirdPartyAppView/ThirdPartyAppView.jsx
- test-result-summary-client/src/ThirdPartyAppView/index.js
- test-result-summary-client/src/utils/TableUtils.jsx
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>
> Add 3rd party application view

- TestResultSummaryService/Database.js
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- TestResultSummaryService/routes/index.js
- TestResultSummaryService/routes/jwt/register.js
- TestResultSummaryService/routes/jwt/verify.js
Users can use api/auth/register to register their info. With the
registration, TRSS will generate a token using JWT (set to expire in
24hrs). Users can send TRSS test results with this token using
api/auth/verify. TRSS will verify the token and return user info.
This is the initial version of the registration and verification. We
will work on the data insertion and display in the future PRs.
> Support registration and verification

- test-result-summary-client/src/Dashboard/Widgets/DateRangePickers.css
- test-result-summary-client/src/Dashboard/Widgets/DateRangePickers.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader7.jsx
Issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/232
- fixed invalid date in DayTrader Graph in Dashboard
- fixed bugs in utils in Graph
- fixed bugs in dateRangePicker.css to fit the position of the date input
> Fixed bugs in Dashboard/Graphs

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/GitNewIssue.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- query build data and test data in the git new issue tab
- add null checking when building URL
> fix long URL of git new issue

- TestResultSummaryService/parsers/Parser.js
- test-result-summary-client/src/Build/GitNewIssue.jsx
- related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/258
Signed-off-by: OscrQQ <Yixin.Qian@ibm.com>
> add artifactory link in git new issue

- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/ThirdPartyAppView/ThirdPartyAppView.jsx
- Unexpected string concatenation of literals  no-useless-concat
- no-unused-vars
> fix client side warnings

- TestResultSummaryService/DataManager.js
- TestResultSummaryService/Database.js
- TestResultSummaryService/parsers/Test.js
- TestResultSummaryService/routes/upsertBuildList.js
> fix deprecated API calls

- test-result-summary-client/src/Build/TestBreadcrumb.jsx
> verify buildId in testBreadCrumb

- TestResultSummaryService/routes/getTestPerPlatform.js
> support AllPlatform for parallel build

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/EventHandler.js
- TestResultSummaryService/routes/deleteBuildData.js
- TestResultSummaryService/routes/deleteBuildListById.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/Settings/Settings.jsx
- original delete icon will automatically delete all build data in DB, and delete URL from monitor list
- add another column Monitoring to let the user choose monitor or not
- add duplicate URL check when the user submit the table
- fixes: #306
> Support user action to delete builds in database

- test-result-summary-client/src/Settings/Settings.jsx
> change info to error icon in monitoring list

- TestResultSummaryService/parsers/Parser.js
> make regex linebreaks more resilient

- TestResultSummaryService/parsers/BenchmarkMetric.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/index.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2122
> enable dacapo in perf dashboard

- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
> validate jdkDate in Dacapo widget

- test-result-summary-client/src/Dashboard/Defaults.js
- test-result-summary-client/src/Dashboard/Widgets/DateRangePickers.css
- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
make date picker work
radio button to filter pipeline
> Improve date picker in Dacapo widget

- .gitignore
- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
- MachineLearningPrototype/data/GitHubData/(sample)openjdk-tests-1820.txt
- MachineLearningPrototype/data/JenkinsData/(sample)openjdk-tests-1820.txt
- MachineLearningPrototype/utils/preprocess_data.py
- Initial prototype to analyze and predict possible issues
- Current code is running in Jupyter Notebook with VS Code
- Related to: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/355
> Initial prototype for deep AQAtik

- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
- filter AdoptOpenJDK and other Jenkins pipeline
- Change test pipleline from checkbox to radio button
- related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2122
> enable radio button in Dacapo widget

- TestResultSummaryService/parsers/BenchmarkMetric.js
related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2122
> add dacapo extended parser

- TestResultSummaryService/parsers/Parser.js
related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/360
> update jdkDate parser regex

- test-result-summary-client/src/Dashboard/Dashboard.jsx
- test-result-summary-client/src/Dashboard/Defaults.js
related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/331
> rename FVT to custom in Dashboard

- .gitignore
- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
- Add function to save trained ML model
- then load and predict with saved model to test
- Related issue: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/355
> Add function to save trained ML model

- test-result-summary-client/src/Build/Summary/ResultGrid.jsx
related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/369
> fix typo in ResultGrid

- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/parsers/Test.js
- related: #307
- together with: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1949
> capture openjdk sha in test builds

- TestResultSummaryService/parsers/Test.js
- test-result-summary-client/src/Build/Summary/ResultGrid.css
Resolve: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/369
> Add background color for ABORTED build

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Add required contrib and code of conduct files
Signed-off-by: Shelley Lambert <slambert@gmail.com>
> Add contrib and code of conduct files

- TestResultSummaryService/README.md
- exportMongo.sh
> TRSS backup story

- test-result-summary-client/src/Dashboard/Defaults.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
- test-result-summary-client/src/Dashboard/Widgets/Settings.jsx
- use array instead of map to store build info
- add hs version and x86-64_mac as more option
> Improve Perf Widget

- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
Fixes #397 
1. Moved `model_comparison_df = model_comparison_df.sort_values(by='f1_scores', ascending=False)` to outside the for loop while training the models to prevent unnecessary sorting after each model (instead sort the values after all the models have been trained).
2. Added cell which demonstrates saving and loading of the model with best performance.
> Save the best model and load it to make predictions

- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
> make dacapo widget fixed title

- test-result-summary-client/src/Build/PossibleIssues.jsx
> Update repo names

- .gitignore
- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
- MachineLearningPrototype/Deployment/deployment.py
- test-result-summary-client/src/Build/PossibleIssues.jsx
- Depoly trained ML model to improve TRSS possible issue function
- TRSS will run normally even ML server is down
- ML training process is also adjusted to suit this deployment
- ReadMe will be added after completing sever setup later
- Related Issue: https://github.com/adoptium/aqa-test-tools/issues/355
> Initial prototype of Machine Learning service deployment

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/TestTable.jsx
> add jenkins link icon at test table

- TestResultSummaryService/parsers/BenchmarkMetric.js
Adding parser for syntheticgc perf test.
Signed-off-by: Awsaf Arefin Sakif <awsaf.sakif@ibm.com>
> Adding metrics for SyntheticGC Perf workload

- test-result-summary-client/src/Build/ReleaseSummary.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader7.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/Renaissance.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
- test-result-summary-client/src/PerfCompare/PerfCompare.jsx
mathjs upgraded from v5 to v7 in https://github.com/adoptium/aqa-test-tools/pull/431.
TRSS code needs to be updated due to mathjs upgrade.
> Update import due to mathjs upgrade

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/routes/deleteBuildData.js
related: https://github.com/AdoptOpenJDK/openjdk-test-tools/issues/322
> delete forever builds if the whole pipeline is deleted

- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/routes/getTabularData.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
- test-result-summary-client/src/TabularView/TabularView.jsx
- mongo store Date object instead of String at databse
-related: #360
> fix jdkDate parser

- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/routes/getTabularData.js
- test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
- test-result-summary-client/src/TabularView/TabularView.jsx
Reverts adoptium/aqa-test-tools#406
> Revert "fix jdkDate parser"

- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
- test-result-summary-client/src/Build/PossibleIssues.jsx
- Update trssml link
- Update os.makedirs option
> Update trssml link

- MachineLearningPrototype/dataCollection/collect_data.py
- MachineLearningPrototype/utils/preprocess_data.py
Added new file to extract the Quoted contents.
Edited the `collect_data.py` file to add new `issue_content_quotation_path` to the MongoDB database
> Added new file to extract output

- test-result-summary-client/src/Build/DeepHistory.jsx
- Add Junit test report link to help users to see more detailed test output (i.e., openjdk tests)
Resolves: https://github.com/adoptium/aqa-test-tools/issues/471
> Add Junit test report link

- MachineLearningPrototype/dataCollection/config.json
- MachineLearningPrototype/utils/preprocess_data.py
Solves #462 
Added a function for getting test info by querying TRSS servers.
> Getting test info from TRSS servers for DeepAQAtik

- TestResultSummaryService/README.md
> Add TRSS sample data

- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
> increase query limit on main page

- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
fixes: https://github.com/adoptium/aqa-test-tools/issues/502
> Change default startBy value to N/A

- MachineLearningPrototype/dataCollection/collect_data.py
- Fix TypeError caused by rate limit exceed
- wait 1 hour to refetch since rate limit is per hour
Related Issue: #498
> Fix rate limit exceeded error

- test-result-summary-client/src/Build/Output/Output.jsx
- test-result-summary-client/src/Build/TestTable.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/Renaissance.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
Edited various files that were showing warnings as mentioned in the issue  [#466](https://github.com/adoptium/aqa-test-tools/issues/466), and all the warnings mentioned in the issue have been removed.
> Removed the warnings

- test-result-summary-client/src/Build/PossibleIssues.jsx
Added the sorter in `Created At` column in Possible Issues column.
Based on #517 .
> Added sorter on Created At column

- TestResultSummaryService/README.md
- TestResultSummaryService/frontend.js
- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
- TestResultSummaryService/routes/getTestAvgDuration.js
- Add express-swagger-generator lib
- Update getTestAvgDuration to use swagger
- Update MongoDB version in package.json
Resolves: https://github.com/adoptium/aqa-test-tools/issues/515
> Add swagger-ui for API

- test-result-summary-client/src/Build/GitNewIssue.jsx
> Apply window origin URL in GitNewIssue

- TestResultSummaryService/nginx.conf
Add sample nginx config in source control. It will help us to keep track of production server configuration.
> Add sample nginx config

- Tweetest/.gitignore
- Tweetest/index.js
- Tweetest/package-lock.json
- Tweetest/package.json
Tasks performed:
- Fetch tweets having hash tags of external_custom
Fixes https://github.com/adoptium/aqa-tests/issues/2785
> Fetch tweets related to external_custom

- TestResultSummaryService/Database.js
- TestResultSummaryService/Dockerfile
- TestResultSummaryService/README.md
- TestResultSummaryService/data/Dockerfile
- docker-compose.yml
- test-result-summary-client/Dockerfile
- test-result-summary-client/package.json
related: https://github.com/adoptium/aqa-test-tools/pull/389
> fix bugs in docker related files

- TestResultSummaryService/routes/getFeedbackUrl.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/Build/PossibleIssues.jsx
The task that have been performed as of now are:
1. Add buttons in display.
2. connect button with function,
3. In the function I have tried to collect various information like issue, issueNum, build Name, build number.
The changes have been made after referencing the suggestions in the issue #496  
> Implemented collect user feedback

- MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
- Modify data path and label  based on new data collection pipeline
- Closes #526
> Modify data path and label to suit data collection pipeline

- test-result-summary-client/src/Build/PossibleIssues.jsx
-related:#507
Signed-off-by: Andi Xiong <xiongandi@gmail.com>
> Show message when no possible issue found

- test-result-summary-client/src/Build/PossibleIssues.jsx
> Display closed issues in Possible Issues view

- test-result-summary-client/src/App.jsx
Signed-off-by: Amanda Nguyen <amanda6@ualberta.ca>
> Updated background color and resized highlighted sections in TRSS

- TestResultSummaryService/routes/getTotals.js
> Adding Swagger definition for getTotals API issue 550

- TestResultSummaryService/routes/getTestByVersionInfo.js
> Add swagger documentation for getTestByVersionInfo API #552.

- TestResultSummaryService/routes/getTestBySearch.js
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Search/SearchOutput.jsx
- test-result-summary-client/src/Search/SearchResult.jsx
- Add advanced global search
- Add search bar on the search page
Resolves: #575
> Add advanced search

- test-result-summary-client/src/Build/Summary/Overview.jsx
> remove the build result

- test-result-summary-client/src/App.jsx
> Reformatted logo and test results summary service

- TestResultSummaryService/routes/getTopLevelBuildNames.js
- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
> Certification page

- test-result-summary-client/cypress/integration/byPipeline.js
- test-result-summary-client/cypress/integration/testInfo.js
Added basic UI checks and loads for the allTestInfo page.
Fixes: #571 
Signed-off-by: Tommy Tho <tommythowm@gmail.com>
> Add tests for TRSS testinfo page

- TestResultSummaryService/Database.js
> Ignore error when the DB collection exists

- TestResultSummaryService/README.md
- TestResultSummaryService/scripts/deployment.sh
> Add deployment script

- test-result-summary-client/src/Build/Output/Output.jsx
Fixes: #597
Signed-off-by: Ying Zhou
> Add jenkins link at build output page

- test-result-summary-client/cypress/integration/byPipeline.js
Added URL check in TRSS Grid View in Cypress unit tests.
Fix: #570 
Signed-off-by: Tommy Tho <tommythowm@gmail.com>
> Add URL check in TRSS Grid view

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
> Move react-app-rewired and react-scripts in dependencies

- test-result-summary-client/src/App.jsx
This updates option AQAvit Certification to AQAvit Verification
before:
After:
Fixes: #636
Signed-off-by: Suhas Khobragade <suhaskhobragade19@gmail.com>
> Update AQAvit Certification to AQAvit Verification #636

- test-result-summary-client/src/Build/ReleaseSummary.jsx
Related: https://github.com/adoptium/aqa-test-tools/issues/657
> Display java -version if it is defined

- test-result-summary-client/src/Build/Summary/ResultGrid.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Resolves: https://github.com/adoptium/aqa-test-tools/issues/661
> Incorporate SDK Build and Smoke Test into Grid view

- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/GitNewIssue.jsx
- test-result-summary-client/src/Build/ReleaseSummary.jsx
- test-result-summary-client/src/Build/Summary/Overview.jsx
- test-result-summary-client/src/TabularView/TabularView.jsx
removed unused components, variables from Overview.js and  BuildDetail.js
removed concatination from GitNewIssue.js and Join it with string literal
replaced map function with forEach in ReleaseSummary.js and TabularView.js
before:
After:
Fixes: 646
Signed-off-by: Suhas Khobragade <suhaskhobragade41@gmail.com>
> Resolve (most of) react lint warnings #646

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
fix: https://github.com/adoptium/aqa-test-tools/issues/671
> Fix build and test name mismatch

- test-result-summary-client/src/Dashboard/Widgets/Graph/AcmeairNodejs.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/DayTrader7.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/ODM.jsx
- test-result-summary-client/src/Dashboard/Widgets/Graph/SPECjbb2015.jsx
fix: https://github.com/adoptium/aqa-test-tools/issues/674
> [TRSS] Fix Dashboard RangeSelector align(#674)

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/Builds.jsx
- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
- test-result-summary-client/src/Build/index.js
resolve: https://github.com/adoptium/aqa-test-tools/issues/488
> Add page for specific build pipeline

- TestResultSummaryService/routes/test/testParser.js
> Update code to be compatible with node v12

- TestResultSummaryService/jenkins/trssCodeSync.groovy
related: https://github.com/adoptium/aqa-test-tools/issues/654
> Sync TRSS code via groovy script

- MachineLearningPrototype/README.md
Changed the spelling of deactiavate to deactivate in [README](https://github.com/adoptium/aqa-test-tools/blob/master/MachineLearningPrototype/README.md) file.
Fixes #689
> Fixed Typo

- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Build/BuildTreeView.jsx
- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
- test-result-summary-client/src/Build/index.js
Issue: https://github.com/adoptium/aqa-test-tools/issues/667
> [TRSS] Add tree view in dashboard

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Related: https://github.com/adoptium/TKG/issues/345
> Add dev level in Grid view

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Fixes: https://github.com/adoptium/aqa-test-tools/issues/698
> Fix criu builds in Grid view

- test-result-summary-client/src/utils/Utils.js
> Add criu in test build regex

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/TestTable.jsx
> Add rerun link in allTestsInfo Page

- test-result-summary-client/src/Build/TestTable.jsx
> Replace all '&amp;' in rerun link

- test-result-summary-client/src/Build/Output/Output.jsx
Add rerun Grinder link in test page and adjust positioning.
resolves: https://github.com/adoptium/aqa-test-tools/issues/723
> Add rerun Grinder link in test page

- test-result-summary-client/src/Build/Summary/BuildStatus.jsx
- test-result-summary-client/src/Build/Summary/BuildStatusIcon.jsx
- test-result-summary-client/src/Build/Summary/Overview.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
- test-result-summary-client/src/utils/Utils.js
> Add build status on grid view

- TestResultSummaryService/routes/getTestBuildsByMachine.js
- TestResultSummaryService/routes/index.js
> Create getTestBuildsByMachine API

- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/parsers/Test.js
- test-result-summary-client/src/Build/ReleaseSummary.jsx
> add Rerun in Grinder with failed test targets in release summary report

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/BuildProcessor.js
> Set Keep Forever for the release builds automatically

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Fix #695 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
> Match x64_alpine-linux to platform x86-64_alpine-linux

- TestResultSummaryService/BuildMonitor.js
- TestResultSummaryService/BuildProcessor.js
Reverts adoptium/aqa-test-tools#743
> Revert "Set Keep Forever for the release builds automatically"

- test-result-summary-client/src/Build/ReleaseSummary.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>
> Skip deep history/possible issues for rerun build in Result Summary Report

- PerfNext/README.md
- TestResultSummaryService/DashboardBuildInfo.json
- TestResultSummaryService/README.md
- test-result-summary-client/src/Dashboard/Defaults.js
- test-result-summary-client/src/TestCompare/TestCompare.jsx
Linked to https://github.com/adoptium/infrastructure/issues/2932
> Change references of ci.adoptopenjdk.net to ci.adoptium.net

- TestResultSummaryService/package-lock.json
- TestResultSummaryService/package.json
Reverts adoptium/aqa-test-tools#772
> Revert "Bump cacheable-request, got and nodemon in /TestResultSummaryService"

- TestResultSummaryService/Dockerfile
- TestResultSummaryService/README.md
- test-result-summary-client/Dockerfile
- test-result-summary-client/src/App.jsx
- test-result-summary-client/src/Dashboard/TabInfo.jsx
- test-result-summary-client/src/Settings/Settings.jsx
Fixes the antd warning shown in the console:
```
Warning: [antd: Menu] children will be removed in next major version. Please use items instead. #1547
```
> update dockerfile to Node 16 and fix antd warnings

- test-result-summary-client/src/Settings/Settings.jsx
@llxia I have no idea why my PR removed these 🤭
> fix Spin not defined

- MachineLearningPrototype/data/JenkinsDataWithFeedback/README.md
- Add JenkinsDataWithFeedback folder for ML issue feedback
- Related Issue: https://github.com/adoptium/aqa-test-tools/issues/496
> Add JenkinsDataWithFeedback folder for ML issue feedback

- .gitignore
- Add JenkinsDataWithFeedback to gitignore
- Related Issue: https://github.com/adoptium/aqa-test-tools/issues/496
> Add JenkinsDataWithFeedback to gitignore

- TestResultSummaryService/parsers/Parser.js
- only parse result summary with no user comment
> Update result summary parser

- docker-compose.yml
resolves: https://github.com/adoptium/aqa-test-tools/issues/802
> Add restart on-failure in docker compose

- Chatbot/.gitignore
- Chatbot/data_1/AQAvit.txt
- Chatbot/data_2/17203.txt
- Chatbot/file.py
- Chatbot/myKeys.sh
Related: https://github.com/adoptium/aqa-test-tools/issues/808
> Initial checkin for Chatbot

- test-result-summary-client/src/utils/Utils.js
related: https://github.com/adoptium/aqa-test-tools/issues/818
> Add support for FIPS140_2 and FIPS_3_YYYYMMDD

- test-result-summary-client/src/Settings/Settings.jsx
resolves: https://github.com/adoptium/aqa-test-tools/issues/817
> Fix Dropdown

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
related: https://github.com/adoptium/aqa-test-tools/issues/839
> Add lazy load

- test-result-summary-client/src/Build/AllTestsInfo.jsx
- test-result-summary-client/src/Build/BuildDetail.jsx
- test-result-summary-client/src/Build/GitNewIssue.jsx
- test-result-summary-client/src/Build/ReleaseSummary.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
Related: https://github.com/adoptium/aqa-test-tools/issues/839
> Use Promise.all() to better handle asynchronous operations

- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/Components/ShowWhenVisible.jsx
> fix loading in pagination

- TestResultSummaryService/Database.js
Add DB index on:
- parentId: 1
- url: 1, buildName: 1, buildNum: 1
related: https://github.com/adoptium/aqa-test-tools/issues/839
> Add DB index

- test-result-summary-client/src/Build/TopLevelBuildTable.jsx
fixes: https://github.com/adoptium/aqa-test-tools/issues/857
> Fix keep forever selection box

- test-result-summary-client/src/AdvancedSearch/AdvancedSearch.jsx
Fix #875 
Added the spinning indicator showing when we click on the button next to the search button.
> Adding the spinning indicator

- TestResultSummaryService/EventHandler.js
Ensure TRSS update/query the status faster
related: infrastructure/issues/9592#issuecomment-86090665
> decrease elasped time

- test-result-summary-client/src/Build/GitNewIssue.jsx
related: internal/backlog/issues/1532
> Update TRSS issue template

- TestResultSummaryService/Database.js
resolves: https://github.com/adoptium/aqa-test-tools/issues/915
> add index for tests.id

- MachineLearningPrototype/data/GitHubData/IssueContent/aqa-tests-1768.txt
- MachineLearningPrototype/data/GitHubData/IssueContentQuote/aqa-tests-1768.txt
- MachineLearningPrototype/data/JenkinsData/aqa-tests_1768_jenkinsData.txt
Add DeepAQAtik data example of aqa-tests repo
> Add DeepAQAtik data example of aqa-tests repo

- test-result-summary-client/src/Build/PossibleIssues.jsx
Fix possible issue query for infra repo
> Fix possible issue query for infra repo

- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/parsers/Test.js
resolves: https://github.com/adoptium/aqa-test-tools/issues/929
> Add test summary from TRSS

- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/utils/Utils.js
fixes: https://github.com/adoptium/aqa-test-tools/issues/932
> Fix build status in Grid view

- test-result-summary-client/package-lock.json
- test-result-summary-client/package.json
- test-result-summary-client/src/Build/GitNewIssue.jsx
resolves: https://github.com/adoptium/aqa-test-tools/issues/939
> Support copy in git new issue page

- test-result-summary-client/src/Build/BuildTreeView.jsx
fixes: #964 
**Before the fix:**
**After the fix:**
**Also tested with "multi-generational hierarchy"** (with fake data):
> fix: rerun builds are correctly nested under their originals in buildTreeView

- test-result-summary-client/src/Build/ReleaseSummary.jsx
- test-result-summary-client/src/Build/Summary/ResultSummary.jsx
- test-result-summary-client/src/Build/TopLevelBuilds.jsx
- test-result-summary-client/src/utils/Utils.js
resovles: https://github.com/adoptium/aqa-test-tools/issues/965
> Fix Perf top Page

- .vscode/launch.json
resolves: https://github.com/adoptium/aqa-test-tools/issues/970
> Enable VSCode TRSS server debugging

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
resolves: automation/issues/228
> Add link from Traffic Light cell to build page

- TestResultSummaryService/routes/getTrafficLightData.js
- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
> Remove regex in getTrafficLightData API

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
resovles: automation/issues/234
> Enlarge traffic light icons on TRSS

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
Add Perf Test and Baseline CI for traffic light
Issue: ibm_git/runtimes/automation/issues/237
> Add Perf Test and Baseline CI for traffic light

- test-result-summary-client/src/App.jsx
fixes: https://github.com/adoptium/aqa-test-tools/issues/994
> Set minHeight to 100vh

- .gitignore
- TestResultSummaryService/Database.js
resolves: automation/issues/295
> Modify index order for TrafficLight page

- test-result-summary-client/src/TrafficLight/MetricsTable.jsx
resolves: automation/issues/296
> Support multiple Perf metrics in adjustable table

- test-result-summary-client/src/TrafficLight/MetricsTable.jsx
- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
resolves: automation/issues/305
> Format perf numbers

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
resolves: automation/issues/360
> Add the top level perf build dropdown

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
Fixes: #1047
TRSS local result:
> Set default top-level performance build.

- TestResultSummaryService/BuildProcessor.js
- TestResultSummaryService/JenkinsInfo.js
resolves: https://github.com/adoptium/aqa-test-tools/issues/1060
> Set Build status to Done when return code is 403

- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
> Fix Perf build default value

- TestResultSummaryService/DataManager.js
- TestResultSummaryService/JenkinsInfo.js
- TestResultSummaryService/parsers/Parser.js
- TestResultSummaryService/parsers/Test.js
related: runtimes/automation/issues/591
> Improve regex in TRSS to handle long line

- TestResultSummaryService/routes/getOutputById.js
related: runtimes/automation/issues/600
> Remove console notes in getOutputById

- .github/workflows/glitchwitcher.yml
- BugPredict/GlitchWitcher/README.md
- BugPredict/GlitchWitcher/extract_traditional_features.sh
- BugPredict/GlitchWitcher/predict.py
- BugPredict/GlitchWitcher/save_trained_model.py
Overview
- Runs GlitchWitcher analysis when a comment containing the trigger is posted on an issue or PR.
- If a dataset for the target repository is missing, the workflow will generate it and open a PR against adoptium/aqa-triage-data. 
Usage / Trigger
- To run analysis on a specific PR:
`GlitchWitcher <PR_link>`
- To run analysis on the same PR where the comment is posted (analyze only C/C++ changes):
`GlitchWitcher`
Behaviour
- Extracts traditional code features for changed files (C/C++ only).
- Uses a trained TensorFlow model (downloads from aqa-triage-data when available) to predict defect-likelihood for files and compares base vs. head.
- If dataset or trained model are missing for the target repo, the workflow:
- Generates dataset,
- Trains a model locally,
- Opens a PR to …
> Add GlitchWitcher workflow

- test-result-summary-client/src/TrafficLight/MetricsTable.jsx
- test-result-summary-client/src/TrafficLight/TrafficLight.jsx
resolves: runtimes/automation/issues/635
> Add java -version info on TRSS metricsDetails page

- TestResultSummaryService/routes/getPossibleIssuesByAI.js
- TestResultSummaryService/routes/index.js
- test-result-summary-client/src/Build/Output/Output.jsx
- test-result-summary-client/src/Build/PossibleIssues.jsx
- test-result-summary-client/src/Build/PossibleIssuesByAI.jsx
This is an initial check-in. We will need to refine the output that gets sent to the AI query.
related: runtimes/automation/issues/657
> Enable AI Recommendation for possible issues

- TestResultSummaryService/routes/getPossibleIssuesByAI.js
- test-result-summary-client/src/Build/PossibleIssuesByAI.jsx
also separate the rationale item per line
related: runtimes/automation/issues/667
> Limit DedupT(AI) query output to 20000 characters
